/*
 * This first example uses a single event handler method (actionPerformed) to
 * provide all the event handling code. Notice how a long-running task is
 * executed on a separate thread, allowing the GUI to be resopnsive even as 
 * another task is being performed. Never put any long-running code in a 
 * GUI event handler without using a separate thread. If you do, you GUI will
 * become unresponsive.
 *
 * Created on Dec 7, 2011, 11:19:48 AM
 */
package tempconvgui;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jlombardo
 */
public class MainWindow extends javax.swing.JFrame implements ActionListener {

    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
        setVisible(true);
        this.setLocationRelativeTo(null);
        //this.getContentPane().setBackground(Color.CYAN);
    }

    private void displayConversion(double converted) throws HeadlessException {
        JOptionPane.showMessageDialog(this, "Conversion: " + converted, 
                "Conversion Result", JOptionPane.INFORMATION_MESSAGE);
    }

    private void displayErrorMsg() throws HeadlessException {
        JOptionPane.showMessageDialog(this, "Sorry, you must enter a numerical value. Please try again", 
                "Data Input Error",
                JOptionPane.ERROR_MESSAGE);
    }

    private double getTemperatureInput(String strTemp, double origTemp) throws HeadlessException {
        try {
            origTemp = Double.parseDouble(strTemp);
        } catch(NumberFormatException nfe) {
            displayErrorMsg();
        }
        return origTemp;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTempGroup = new javax.swing.ButtonGroup();
        btnConvert = new javax.swing.JButton();
        this.getRootPane().setDefaultButton(btnConvert);
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rdoFahrenheitToCelcius = new javax.swing.JRadioButton();
        rdoCelciusToFahrenheit = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtTemp = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Cnverter v1.00");
        setBackground(new java.awt.Color(255, 255, 204));
        setIconImage(getIconImage());
        setResizable(false);

        btnConvert.setText("Convert");
        btnConvert.addActionListener(this);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Temperature Converter");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Conversion Type"));

        btgTempGroup.add(rdoFahrenheitToCelcius);
        rdoFahrenheitToCelcius.setSelected(true);
        rdoFahrenheitToCelcius.setText("Fahrenheit to Celcius");

        btgTempGroup.add(rdoCelciusToFahrenheit);
        rdoCelciusToFahrenheit.setText("Celcius to Fahrenheit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoCelciusToFahrenheit)
                    .addComponent(rdoFahrenheitToCelcius))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rdoFahrenheitToCelcius)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdoCelciusToFahrenheit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Temperature");

        txtTemp.setText("0.00");

        btnExit.setText("Exit");
        btnExit.addActionListener(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConvert)
                    .addComponent(btnExit))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == btnConvert) {
            MainWindow.this.btnConvertActionPerformed(evt);
        }
        else if (evt.getSource() == btnExit) {
            MainWindow.this.btnExitActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        // TODO add your handling code here:
        String strTemp = this.txtTemp.getText();
        double origTemp = 0.0;
        double converted = 0.0;
        
        if(this.rdoFahrenheitToCelcius.isSelected()) {
            origTemp = getTemperatureInput(strTemp, origTemp);
            converted = (origTemp - 32) * 5/9;
            displayConversion(converted);
        } else {
            origTemp = getTemperatureInput(strTemp, origTemp);
            converted = origTemp * 9/5 + 32;
            displayConversion(converted);
        }
        
        // now perform an operation that takes a lot of time
        // by running it in a separate thread
        new Thread(new Runnable() {
            public void run() {
                for(long l=0; l < 1000000000000L; l++) {
                    System.out.println("Long running iteration #" + l);
                }
            }
        }).start();

    }//GEN-LAST:event_btnConvertActionPerformed

    
    
    
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    
    //Returns an Image or null.
    @Override
    public Image getIconImage() {
        java.net.URL imgURL = MainWindow.class.getResource("images/logo.gif");
        if (imgURL != null) {
            return new ImageIcon(imgURL).getImage();
        } else {
            return null;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgTempGroup;
    private javax.swing.JButton btnConvert;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdoCelciusToFahrenheit;
    private javax.swing.JRadioButton rdoFahrenheitToCelcius;
    private javax.swing.JTextField txtTemp;
    // End of variables declaration//GEN-END:variables
}
